# 1. Import Libraries

In [1]:
# Importing libraries
import pandas as pd
import numpy as np
import os

# 2. Import Data

In [5]:
# Folder path:
path = r'C:\Users\Kamron\Downloads\Achievement 4'

In [6]:
# Import products.csv:
df_prods = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'products.csv'), index_col = False)

In [7]:
# Import orders_wrangled.csv

df_ords = pd.read_csv(os.path.join(path, '02 Data', 'Prepared Data', 'orders_wrangled.csv'), index_col = False)

# Consistency Check

### Mixed-Type Data

In [9]:
# Create a new test dataframe
df_test = pd.DataFrame()

In [10]:
# Create a new test dataframe
df_test['mix'] = ['a', 'b', 1, True]

In [11]:
df_test.head()

mix
0     a
1     b
2     1
3  True

In [12]:
# Check for mixed types

for col in df_test.columns.tolist():
    weird = (df_test[[col]].applymap(type) != df_test[[col]].iloc[0].apply(type)).any(axis = 1)
    if len (df_test[weird]) > 0:
        print (col)

mix


In [13]:
for col in df_test.columns.tolist():
    weird = (df_test[[col]].applymap(type) != df_test[[col]].iloc[0].apply(type)).any(axis = 1)
    if len (df_test[weird]) > 0:
        print (col, 'mixed')
    else: print(col, 'consistent')

mix mixed


In [14]:
# Changing data type to string
df_test['mix'] = df_test['mix'].astype('str')

In [15]:
# Recheck for mixed data type

for col in df_test.columns.tolist():
    weird = (df_test[[col]].applymap(type) != df_test[[col]].iloc[0].apply(type)).any(axis = 1)
    if len (df_test[weird]) > 0:
        print (col, 'mixed')
    else: print(col, 'consistent')

mix consistent


### Missing Values

In [16]:
df_prods.isnull().sum()

product_id        0
product_name     16
aisle_id          0
department_id     0
prices            0
dtype: int64

In [17]:
# To actually view these 16 values, you can create a subset of the dataframe

df_nan = df_prods[df_prods["product_name"].isnull() == True]

In [18]:
df_nan

product_id product_name  aisle_id  department_id  prices
33             34          NaN       121             14    12.2
68             69          NaN        26              7    11.8
115           116          NaN        93              3    10.8
261           262          NaN       110             13    12.1
525           525          NaN       109             11     1.2
1511         1511          NaN        84             16    14.3
1780         1780          NaN       126             11    12.3
2240         2240          NaN        52              1    14.2
2586         2586          NaN       104             13    12.4
3159         3159          NaN       126             11    13.1
3230         3230          NaN       120             16    14.4
3736         3736          NaN        41              8    14.8
4283         4283          NaN        77              7    14.4
4790         4790          NaN        91             16    14.5
38187       38183          NaN        39             12    20.9
40444       40440          NaN       120             16    14.8

### Addressing Missing Values

In [19]:
df_prods.describe()

product_id      aisle_id  department_id        prices
count  49693.000000  49693.000000   49693.000000  49693.000000
mean   24844.345139     67.770249      11.728433      9.994136
std    14343.717401     38.316774       5.850282    453.519686
min        1.000000      1.000000       1.000000      1.000000
25%    12423.000000     35.000000       7.000000      4.100000
50%    24845.000000     69.000000      13.000000      7.100000
75%    37265.000000    100.000000      17.000000     11.200000
max    49688.000000    134.000000      21.000000  99999.000000

In [21]:
# Checking the number of rows in product dataframe
df_prods.shape

(49693, 5)

In [22]:
# Creating a new dataframe for non missing value
df_prods_clean = df_prods[df_prods['product_name'].isnull() == False]

In [23]:
df_prods_clean.shape

(49677, 5)

In [24]:
# Looking for duplicates in products dataframe
df_dups = df_prods_clean[df_prods_clean.duplicated()]

In [25]:
df_dups

product_id                                       product_name  \
462           462                  Fiber 4g Gummy Dietary Supplement   
18459       18458                                         Ranger IPA   
26810       26808               Black House Coffee Roasty Stout Beer   
35309       35306  Gluten Free Organic Peanut Butter & Chocolate ...   
35495       35491                            Adore Forever Body Wash   

       aisle_id  department_id  prices  
462          70             11     4.8  
18459        27              5     9.2  
26810        27              5    13.4  
35309       121             14     6.8  
35495       127             11     9.9

In [26]:
# Creating new dataframe without duplicates
df_prods_clean_no_dups = df_prods_clean.drop_duplicates()

In [27]:
df_prods_clean_no_dups.shape

(49672, 5)

In [28]:
# Exporting new dataframe as products_checked
df_prods.to_csv(os.path.join(path, '02 Data', 'Prepared Data', 'products_checked.csv'))

# 4.5: Data Consistency Checks

In [29]:
# Step 2: Run the df.describe() function on your df_ords dataframe:
df_prods.describe()

product_id      aisle_id  department_id        prices
count  49693.000000  49693.000000   49693.000000  49693.000000
mean   24844.345139     67.770249      11.728433      9.994136
std    14343.717401     38.316774       5.850282    453.519686
min        1.000000      1.000000       1.000000      1.000000
25%    12423.000000     35.000000       7.000000      4.100000
50%    24845.000000     69.000000      13.000000      7.100000
75%    37265.000000    100.000000      17.000000     11.200000
max    49688.000000    134.000000      21.000000  99999.000000

Question 2: Min value = 1.000000, Max value 99999.000000. Possibly selling diamond candy bars

In [30]:
df_prods[df_prods.prices == 99999]

product_id           product_name  aisle_id  department_id   prices
33666       33664  2 % Reduced Fat  Milk        84             16  99999.0

In [1]:
df_prods[df_prods.prices == 99999] = 9.99

In [7]:
df_prods.describe()

product_id      aisle_id  department_id        prices
count  49693.000000  49693.000000   49693.000000  49693.000000
mean   24843.667901     67.768760      11.728312      7.982001
std    14344.095455     38.317582       5.850255     66.937784
min        1.000000      1.000000       1.000000      1.000000
25%    12422.000000     35.000000       7.000000      4.100000
50%    24844.000000     69.000000      13.000000      7.100000
75%    37265.000000    100.000000      17.000000     11.200000
max    49688.000000    134.000000      21.000000  14900.000000

In [8]:
df_prods[df_prods.prices == 14900]

product_id                      product_name  aisle_id  department_id  \
21554     21553.0  Lowfat 2% Milkfat Cottage Cheese     108.0           16.0   

        prices  
21554  14900.0

In [9]:
df_prods[df_prods.prices == 14900] = 1.49

In [10]:
df_prods.describe()

product_id      aisle_id  department_id        prices
count  49693.000000  49693.000000   49693.000000  49693.000000
mean   24843.234208     67.766617      11.728020      7.682190
std    14344.520748     38.318310       5.850404      4.200262
min        1.000000      1.000000       1.000000      1.000000
25%    12421.000000     35.000000       7.000000      4.100000
50%    24844.000000     69.000000      13.000000      7.100000
75%    37265.000000    100.000000      17.000000     11.200000
max    49688.000000    134.000000      21.000000     25.000000

That looks normal!

In [31]:
# Step 3: Check for mixed-type data in your df_ords dataframe:
for col in df_ords.columns.tolist():
    weird = (df_ords[[col]].applymap(type) != df_ords[[col]].iloc[0].apply(type)).any(axis = 1)
    if len (df_ords[weird]) > 0:
        print (col, 'mixed')
    else: print(col, 'consistent')

Unnamed: 0 consistent
order_id consistent
user_id consistent
eval_set consistent
order_number consistent
orders_day_of_week consistent
order_hour_of_day consistent
days_since_last_order consistent


In [32]:
# Step 4. If you find mixed-type data, fix it:

The column in question should contain observations of a single data type:
No mixed-type data found. 

In [33]:
# Step 5. Run a check for missing values in your df_ords dataframe:
df_ords.isnull().sum()

Unnamed: 0                    0
order_id                      0
user_id                       0
eval_set                      0
order_number                  0
orders_day_of_week            0
order_hour_of_day             0
days_since_last_order    206209
dtype: int64

In [34]:
df_ords.head(20)

Unnamed: 0  order_id  user_id eval_set  order_number  orders_day_of_week  \
0            0   2539329        1    prior             1                   2   
1            1   2398795        1    prior             2                   3   
2            2    473747        1    prior             3                   3   
3            3   2254736        1    prior             4                   4   
4            4    431534        1    prior             5                   4   
5            5   3367565        1    prior             6                   2   
6            6    550135        1    prior             7                   1   
7            7   3108588        1    prior             8                   1   
8            8   2295261        1    prior             9                   1   
9            9   2550362        1    prior            10                   4   
10          10   1187899        1    train            11                   4   
11          11   2168274        2    prior             1                   2   
12          12   1501582        2    prior             2                   5   
13          13   1901567        2    prior             3                   1   
14          14    738281        2    prior             4                   2   
15          15   1673511        2    prior             5                   3   
16          16   1199898        2    prior             6                   2   
17          17   3194192        2    prior             7                   2   
18          18    788338        2    prior             8                   1   
19          19   1718559        2    prior             9                   2   

    order_hour_of_day  days_since_last_order  
0                   8                    NaN  
1                   7                   15.0  
2                  12                   21.0  
3                   7                   29.0  
4                  15                   28.0  
5                   7                   19.0  
6                   9                   20.0  
7                  14                   14.0  
8                  16                    0.0  
9                   8                   30.0  
10                  8                   14.0  
11                 11                    NaN  
12                 10                   10.0  
13                 10                    3.0  
14                 10                    8.0  
15                 11                    8.0  
16                  9                   13.0  
17                 12                   14.0  
18                 15                   27.0  
19                  9                    8.0

In [36]:
df_ords['user_id'] = df_ords['user_id'].astype('int64')
df_ords.user_id.max()

206209

In [40]:
df_ords = df_ords.drop(columns = ['Unnamed: 0'])

In [45]:
df_ords.isnull().sum()

order_id                      0
user_id                       0
eval_set                      0
order_number                  0
orders_day_of_week            0
order_hour_of_day             0
days_since_last_order    206209
dtype: int64

In [47]:
# Create a dataframe for the missing values
df_ords_nan = df_ords [df_ords ['days_since_last_order'].isnull () == True]

In [48]:
 df_ords_nan

order_id  user_id eval_set  order_number  orders_day_of_week  \
0         2539329        1    prior             1                   2   
11        2168274        2    prior             1                   2   
26        1374495        3    prior             1                   1   
39        3343014        4    prior             1                   6   
45        2717275        5    prior             1                   3   
...           ...      ...      ...           ...                 ...   
3420930    969311   206205    prior             1                   4   
3420934   3189322   206206    prior             1                   3   
3421002   2166133   206207    prior             1                   6   
3421019   2227043   206208    prior             1                   1   
3421069   3154581   206209    prior             1                   3   

         order_hour_of_day  days_since_last_order  
0                        8                    NaN  
11                      11                    NaN  
26                      14                    NaN  
39                      11                    NaN  
45                      12                    NaN  
...                    ...                    ...  
3420930                 12                    NaN  
3420934                 18                    NaN  
3421002                 19                    NaN  
3421019                 15                    NaN  
3421069                 11                    NaN  

[206209 rows x 7 columns]

In [49]:
# Step 6. Address the missing values using an appropriate method:

Since this data is related to stock and merchandise, it would be unwise to remove, duplicate, suppress, supplement, or replace the missing values. Rather, leaving the values alone for now will give better results later in regards to the stocks inventory.

In [50]:
# Step 7. Run a check for duplicate values in your df_ords data:
df_ords_dups = df_ords[df_ords.duplicated()]

In [51]:
df_ords_dups.size

0

No duplicates found

In [52]:
# Step 8. Address the duplicates using an appropriate method:

There are no duplicates to address

In [53]:
# Export final df_ords 

df_ords.to_csv(os.path.join(path, '02 Data','Prepared Data', 'orders_checked.csv'))